# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HuliCli < Formula
  desc "Command-line client for the Huli Public FHIR R4 + R5 API"
  homepage "https://developers.huli.ai/v1/cli/"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hulilabs/cli/releases/download/v0.0.2/huli_0.0.2_darwin_amd64.tar.gz"
      sha256 "1903037aaf0cc7c5d8281b8b0d760baa303832c6631e83c606c0509e008a6888"

      define_method(:install) do
        bin.install "huli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hulilabs/cli/releases/download/v0.0.2/huli_0.0.2_darwin_arm64.tar.gz"
      sha256 "cd9426e61fc8a55c4755a2b2a2ef461f2e75f1e09c9ae4d744746b854ac97027"

      define_method(:install) do
        bin.install "huli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hulilabs/cli/releases/download/v0.0.2/huli_0.0.2_linux_amd64.tar.gz"
      sha256 "e8933c84a37caa16d36420d373616fd8b7c363ebd4c44e6f72621f259b159e44"
      define_method(:install) do
        bin.install "huli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hulilabs/cli/releases/download/v0.0.2/huli_0.0.2_linux_arm64.tar.gz"
      sha256 "ab0e89dac127a1af80edd5c5d1408819fe043121ac1db6407cfe7b7e5cb13adb"
      define_method(:install) do
        bin.install "huli"
      end
    end
  end

  test do
    system "#{bin}/huli", "version"
  end
end
